global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: node-exporter
    static_configs:
      - targets: ["host.docker.internal:9100"]
  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8087"]
  - job_name: app-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8088"]